server:
  port: 81
spring:
  application:
    name: nacos-consumer-service
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
service-url:
  nacos-user-service: http://nacos-pay-service
feign:
  sentinel:
    enabled: true